#:schema ../node_modules/wrangler/config-schema.json

name = "remix-login-api"
main = "index.ts"
compatibility_date = "2024-09-09"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "remix-login"
database_id = "08d177d9-9450-47cd-bbb4-e86bf8975df8"